spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: route1
              uri: lb://CUSTOMER-SERVICE
              predicates:
                - Path=/customers/**
            - id: route2
              uri: lb://INVENTORY-SERVICE
              predicates:
                - Path=/products/**